server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /movies {
        proxy_pass http://backend:3000;
    }

    location /reservations {
        proxy_pass http://backend:3000;
    }

    location /health {
        proxy_pass http://backend:3000;
    }
}